# Generated by Django 5.1.7 on 2025-07-02 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudo',
            name='id',
            field=models.CharField(db_default='uuid()', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kudo',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_kudos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kudo',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_kudos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(db_default='uuid()', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_default='uuid()', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
